### ISSUE TITLE
Migrating docs from client-side to server-side

### ISSUE THREAD

**Issue by Avi98** [siddharthkp/react-ui#102]
Hi @siddharthkp , server-side rendering of docs can help in SEO and [other issues](https://github.com/siddharthkp/react-ui/issues/95) that it is facing right now. I can start rewriting the same in Next.js. Anything specific that I need to keep in mind

**Comment by siddharthkp** [comment]
I think it's too early to optimise for seo given the project docs aren't fleshed out :) But, this would be a good issue to come back in a couple of months
