### ISSUE TITLE
Next.js: Global CSS cannot be imported from within node_modules.

### ISSUE THREAD

**Issue by jacob-ruiz** [siddharthkp/react-ui#11]
Hi there, I'm really excited about react-ui. 

I'm trying to get it set up in my Next.js project, and I'm getting the following error: 

`./node_modules/@reach/menu-button/styles.css
Global CSS cannot be imported from within node_modules.
Read more: https://err.sh/next.js/css-npm
Location: node_modules/react-ui/dist/index.js`

The "Read more" link from Zeit says "[Reach out to the maintainer and ask for them to publish a compiled version of their dependency.](https://err.sh/next.js/css-npm)"

Do you have a recommendation about how to fix this to get react-ui working with Next? Sorry if I'm missing something obvious.

Thanks for your great work on this!

**Comment by siddharthkp** [comment]
This is a really good bug report! I'll look into it 💯

**Comment by siddharthkp** [comment]
Hey!

Figured out how to bundle this properly, released in react-ui@1.0.0-beta.21

Thanks for reporting this :)

**Comment by jacob-ruiz** [comment]
Boom! Works great, thanks for the quick turnaround.

Sharing a bare-bones Next.js + React UI example setup in case anyone comes across this: https://codesandbox.io/s/next-react-ui-d3o1n
