### ISSUE TITLE
Copy button seems to be overlapping with the scroll bar.

### ISSUE THREAD

**Issue by abhinav-anshul** [siddharthkp/react-ui#18]
The copy button on the [Components](https://react-ui.dev/components) page seems to be overlapping with the scroll bar. It needs to have more width area.

Please refer to the provided image for reference: 

![react-ui-copy-button](https://user-images.githubusercontent.com/26833319/78660553-e8b3cf80-78ea-11ea-9abf-8ab85558df29.PNG)

**Comment by siddharthkp** [comment]
aaaaah, there shouldn't be a scrollbar there 🤔 What browser + OS is that?

**Comment by abhinav-anshul** [comment]
I am using Chrome in Window Operating System

**Comment by siddharthkp** [comment]
I want to say changing [this line in the docs](https://github.com/siddharthkp/react-ui/blob/master/packages/docs/src/components/example.js#L128) to 'auto' would fix this

Would you like to create a pull request?

**Comment by abhinav-anshul** [comment]
Yes sure, on it!

**Comment by rubenmoya** [comment]
Fixed in https://github.com/siddharthkp/react-ui/pull/19 🎉
