### ISSUE TITLE
RTL support in <Stack/>

### ISSUE THREAD

**Issue by Andarist** [siddharthkp/react-ui#20]
It would be great if `<Stack/>` could support rtl layout. It's simple on the surface - we just need to render marginLeft instead of marginRight, but there is no good CSS way of knowing if you are in RTL context, so this most likely would require adding also a special prop to accommodate this.

**Comment by alxrocha** [comment]
This is a great use case for CSS logical properties. Using `margin-inline-start` would work (not supported on any IE version: [caniuse](https://caniuse.com/#feat=css-logical-props).
Another solution, change the underlying implementation from flexbox to CSS Grid and use `grid-gap` for the spacing.

**Comment by siddharthkp** [comment]
AFAIK, IE doesn't support grid-gap either 😓 

I'm okay with dropping IE support, `margin-inline-start` would be closed to the margin approach

**Comment by Andarist** [comment]
If you are good with dropping support for IE then `margin-inline-end` looks like a good solution. From what I can tell based on https://caniuse.com/#feat=css-logical-props it has good browser support. I would only probably recommend using also its prefixed version `-webkit-margin-end` because Emotion v10 doesn't prefix this property automatically (upcoming v11 will do it though).

**Comment by siddharthkp** [comment]
Sounds like a good plan to me. Up for grabs.
