### ISSUE TITLE
Codebase build/dev process is unclear

### ISSUE THREAD

**Issue by NateRadebaugh** [siddharthkp/react-ui#22]
While yarn workspaces are being used, it's unclear what the expected process is for build/dev of the codebase. This makes it difficult to contribute to the codebase since it's harder to get ramped up and verify changes.

The root `package.json` file should have a `build` and `dev` scripts to build/setup all the workspaces for quick iteration and validation.

**Comment by siddharthkp** [comment]
Added a [CONTRIBUTING.md](https://github.com/siddharthkp/react-ui/blob/master/CONTRIBUTING.md), would love to get your feedback.
