### ISSUE TITLE
"Anonymous" components during development

### ISSUE THREAD

**Issue by rubenmoya** [siddharthkp/react-ui#34]
Since we're using anonymous functions to create the components they render as `Anonymous` in the React Devtools during development, should we add a `displayName` to them?

If so, we don't need this in production (same as the proptypes) we could use something like [rollup/replace](https://github.com/rollup/plugins/tree/master/packages/replace) to avoid that code being added to the final bundle.

Since we're adding `forwardRef` another option could be to return a named function:

```jsx
const Button = React.forwardRef(function Button(props, ref) {
...
})
```

![image](https://user-images.githubusercontent.com/905225/79139225-367e7b00-7db6-11ea-956e-a03b3340a9a7.png)

**Comment by siddharthkp** [comment]
```js
const Button = React.forwardRef(function Button(props, ref)
```

Sounds very reasonable to do this. 👍

**Comment by rubenmoya** [comment]
We could tackle this in the forwardRef PR since I'll need to touch all of them 😂

**Comment by siddharthkp** [comment]
#33 takes care of this :)

https://github.com/siddharthkp/react-ui/pull/33
