### ISSUE TITLE
Popup or Dialog component

### ISSUE THREAD

**Issue by loweisz** [siddharthkp/react-ui#38]
Are there any plans or ideas to add a simple popup or Dialog component?

**Comment by siddharthkp** [comment]
Yep, definitely on my list 😀

**Comment by loweisz** [comment]
Would it be free for contribution ? 😃

**Comment by siddharthkp** [comment]
Yeah, go for it :)

I highly recommend using [reach-ui/dialog](https://reacttraining.com/reach-ui/dialog/) as the base

**Comment by loweisz** [comment]
Opened the PR for it: #39. Feel free to add any suggestions or ideas 😃

**Comment by rubenmoya** [comment]
Can we close this?

**Comment by siddharthkp** [comment]
Oh yeah!
