### ISSUE TITLE
Fix Stack specificity issues

### ISSUE THREAD

**Issue by siddharthkp** [siddharthkp/react-ui#40]
When you put elements in a Stack with gap, the gap overrides the margins on individual elements because it has higher specificity. (example in codesandbox link below)

But, if we use the [lobotomized owl selector](https://css-tricks.com/spacing-the-bottom-of-modules/), we can solve this! 

I had completely forgot about the lobotomized owl, that article ⬆️ is from 2013! and was reminded of it [from a tweet](https://twitter.com/adamwathan/status/1250583225757569027) by @adamwathan! cheers to him!

Repro and suggested fix (Stack 2): https://codesandbox.io/s/infallible-proskuriakova-5zwzg

**Comment by Sagarpreet** [comment]
Hey can i take this up?

**Comment by siddharthkp** [comment]
@Sagarpreet Sure, go for it
