### ISSUE TITLE
Add example of using 3rd party components with react-ui

### ISSUE THREAD

**Issue by siddharthkp** [siddharthkp/react-ui#41]
Leaving this here because I will forget!

1. react-router
2. something from reach-ui
3. something from reakit

**Comment by jgoux** [comment]
I think a custom jsx pragma would be of great help for this.

**Comment by siddharthkp** [comment]
Fixed in #41 :)

**Comment by siddharthkp** [comment]
@jgoux Never implemented a pragma before, Can you point me in the direction to learn more
