### ISSUE TITLE
Dropdown Menu component defaults to first item focused/selected

### ISSUE THREAD

**Issue by JalDEV** [siddharthkp/react-ui#58]
Take a look at the theme picker on your website for an example. The drop down is defaulting to focus the first item, regardless of what was selected. The expected behavior would be that the currently selected item is focused when the menu is open. 

Chrome/Safari iOS at least, haven’t tested on other browsers.

**Comment by siddharthkp** [comment]
This is already fixed in reach/menu-button@0.10.1 🎉 Kudos to @cpmsmith

We can update the dependency and we're good! Up for grabs

**Comment by JalDEV** [comment]
FYI do you guys need any help with this library?

**Comment by siddharthkp** [comment]
@JalDEV could always use an extra hand :)
