### ISSUE TITLE
Broken Images on Components page

### ISSUE THREAD

**Issue by iamdarshshah** [siddharthkp/react-ui#66]
- [ ] Theme Provider

- [ ] Tooltip 

Refer:
![Screenshot (3)](https://user-images.githubusercontent.com/25670841/81265993-a2749c00-9061-11ea-844f-51e7186619c2.png)
![Screenshot (4)](https://user-images.githubusercontent.com/25670841/81265998-a3a5c900-9061-11ea-8ea6-a9a1ed96325c.png)

**Comment by rubenmoya** [comment]
It seems that it broke because of the changes to make the favicon change based on the theme, nice catch!

**Comment by siddharthkp** [comment]
Nice catch! I think I broke this last night without realising

**Comment by siddharthkp** [comment]
Fixed in https://github.com/siddharthkp/react-ui/pull/67
