### ISSUE TITLE
Issue with Dark Theme - styling of different element needs to be changed

### ISSUE THREAD

**Issue by iamdarshshah** [siddharthkp/react-ui#72]
Steps to Reproduce: 

1. change the theme to Dark
2. hover on any of these elements/components:

**Refer:**

- [ ] Paragraph
![Screenshot (15)](https://user-images.githubusercontent.com/25670841/81411606-3fb5fa00-9160-11ea-97ca-47a1693a0b35.png)

- [ ] Menu
![Screenshot (16)](https://user-images.githubusercontent.com/25670841/81411649-4cd2e900-9160-11ea-9a96-38b465268ffb.png)

- [ ] Heading
![Screenshot (12)](https://user-images.githubusercontent.com/25670841/81411705-62481300-9160-11ea-9b4a-db3f8ebeaa02.png)

- [ ] Element
![Screenshot (10)](https://user-images.githubusercontent.com/25670841/81411746-6e33d500-9160-11ea-94db-b315972fb1c6.png)

> Issue is with the Dark theme stylings: child component stylings are the same as of the parent component (when we hover). Thus, we need to change the **hover** property stylings to make it visible clearly.

**Comment by siddharthkp** [comment]
Thanks for reporting the issue. This is a great bug report which points the problem really fast!
