### ISSUE TITLE
Issue with theme change while redirecting to different page

### ISSUE THREAD

**Issue by iamdarshshah** [siddharthkp/react-ui#87]
- **Steps to reproduce:**

1.  visit the site `https://react-ui.dev/`
2. Change the theme from `Light to Dark`
3. then visit any of these links from `Start here:` section
![Capture](https://user-images.githubusercontent.com/25670841/82062871-61772a00-96e8-11ea-830a-64340cb6e4df.PNG)

> You will notice theme change after we are redirected.

- **Expected Behaviour**

`Theme should not change unless and until the user changes it manually. It should be set globally.`

**Comment by ankibalyan** [comment]
Duplicate of #44

**Comment by iamdarshshah** [comment]
Okay, will have a look at it and closing this for now. thanks @ankibalyan
