### ISSUE TITLE
Documentation Issue

### ISSUE THREAD

**Issue by jsrikrishna11** [siddharthkp/react-ui#89]
This page has no content.

https://react-ui.dev/core-concepts/tokens

<img width="1439" alt="Screenshot 2020-05-16 at 3 25 56 PM" src="https://user-images.githubusercontent.com/41172782/82116757-97b8b600-9789-11ea-8416-ee0c227b5780.png">

**Comment by siddharthkp** [comment]
Haha, yep, still filling out some of these pages :) Documentation is hard!

**Comment by siddharthkp** [comment]
Closing this issue because i'm tracking documentation tasks in a different place
